// Code generated by mockery v2.44.1. DO NOT EDIT.

package binding

import (
	binding "github.com/Alwanly/go-codebase/pkg/binding"
	mock "github.com/stretchr/testify/mock"
)

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockSource) Execute(_a0 *binding.Binder) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*binding.Binder) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSource_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSource_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *binding.Binder
func (_e *MockSource_Expecter) Execute(_a0 interface{}) *MockSource_Execute_Call {
	return &MockSource_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockSource_Execute_Call) Run(run func(_a0 *binding.Binder)) *MockSource_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*binding.Binder))
	})
	return _c
}

func (_c *MockSource_Execute_Call) Return(_a0 error) *MockSource_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSource_Execute_Call) RunAndReturn(run func(*binding.Binder) error) *MockSource_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
